# Generated by Django 3.0.3 on 2020-09-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='Requester',
            new_name='user',
        ),
    ]
