# Generated by Django 3.0.3 on 2020-09-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200908_2209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInformation',
            new_name='Contact',
        ),
    ]
