# Generated by Django 3.0.3 on 2020-09-10 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200909_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Contact'),
        ),
    ]
