# Generated by Django 3.0.3 on 2020-09-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200909_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
